INSERT INTO exercices_reference (nom_fr, categorie, groupe_analyse, qualite_cible, unite, ratio_base, ratio_avance, ratio_elite) VALUES
('Épaulé (Clean)', 'Haltérophilie', 'Groupe Clean', 'Explosivité', 'kg', 0.7, 1.35, 1.6),
('Power Clean', 'Haltérophilie', 'Groupe Clean', 'Explosivité', 'kg', 0.7, 1.3, 1.5),
('Arraché (Snatch)', 'Haltérophilie', 'Groupe Snatch', 'Explosivité', 'kg', 0.6, 1.0, 1.25),
('Épaulé-jeté (Clean & Jerk)', 'Haltérophilie', 'Groupe Clean & Jerk', 'Explosivité', 'kg', 0.8, 1.5, 1.75),
('Squat Arrière (Back Squat)', 'Muscu. Bas', 'Groupe Squat', 'Force Maximale', 'kg', 1.0, 1.8, 2.2),
('Squat Avant (Front Squat)', 'Muscu. Bas', 'Groupe Squat', 'Force Maximale', 'kg', 0.8, 1.5, 1.8),
('Soulevé de Terre (Deadlift)', 'Muscu. Bas', 'Groupe SDT', 'Force Maximale', 'kg', 1.2, 2.2, 2.6),
('Soulevé de Terre Roumain (RDL)', 'Muscu. Bas', 'Groupe SDT Accessoire', 'Force (Chaîne Postérieure)', 'kg', 0.9, 1.6, 1.9),
('Hip Thrust', 'Muscu. Bas', 'Groupe Hip Thrust', 'Force (Chaîne Postérieure)', 'kg', 1.2, 2.3, 3.0),
('Presse à Cuisses (Leg Press)', 'Muscu. Bas', 'Groupe Presse', 'Force (Hypertrophie)', 'kg', 2.0, 3.5, 4.5),
('Good Mornings', 'Muscu. Bas', 'Groupe Acc. Post.', 'Force (Stabilité)', 'kg', 0.4, 0.8, 1.0),
('Développé Couché', 'Muscu. Haut', 'Groupe Couché', 'Force Maximale', 'kg', 0.8, 1.3, 1.5),
('Développé Militaire', 'Muscu. Haut', 'Groupe Press', 'Force (Haut du Corps)', 'kg', 0.5, 0.8, 1.0),
('Tractions Lestées', 'Muscu. Haut', 'Groupe Traction', 'Force (Haut du Corps)', 'kg', 0.1, 0.4, 0.7),
('Dips Lestés', 'Muscu. Haut', 'Groupe Dips', 'Force (Haut du Corps)', 'kg', 0.2, 0.5, 0.8),
('Squat Bulgare (Split Squat)', 'Unilatéral', 'Groupe Unilatéral Bas', 'Force (Unilatéral)', 'kg', 0.4, 0.8, 1.0),
('Fentes (Marchées ou Statiques)', 'Unilatéral', 'Groupe Unilatéral Bas', 'Force (Unilatéral)', 'kg', 0.3, 0.7, 0.9),
('Saut Vertical (Détente Sèche)', 'Pliométrie', 'Groupe Saut Vertical', 'Pliométrie', 'cm', 40, 65, 80),
('Saut en Longueur (Sans Élan)', 'Pliométrie', 'Groupe Saut Horizontal', 'Pliométrie', 'cm', 220, 270, 300),
('Lancer Médecine Ball (Arr. 2kg)', 'Lancers', 'Groupe Lancer Léger', 'Explosivité', 'm', 5, 8, 12),
('Lancer Poids (Arr. 7.26kg)', 'Lancers', 'Groupe Lancer Lourd', 'Force Explosive', 'm', 6, 10, 13);